apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-index
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-index
  namespace: demo
data:
  index.html: |
    <html>
    <body>
      <h1>Frontend (NGINX)</h1>
      <p>Calls backend at <code>http://backend:3000</code></p>
      <p><a href="/health">frontend health</a></p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-headless
  namespace: demo
spec:
  clusterIP: None
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
